/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.100
 * Generated at: 2025-03-26 07:49:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class jsp022_005flogin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1742950788682L));
    _jspx_dependants.put("/jsp022_header3.jsp", Long.valueOf(1742951962598L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!-- login.jsp -->    \r\n");
      out.write("<!-- login.jsp -->    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html  lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<!-- Latest compiled and minified CSS -->\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Latest compiled JavaScript -->\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- navrbar -->\r\n");
      out.write("<!-- navrbar -->\r\n");
      out.write("\r\n");
      out.write("	<nav class=\"navbar navbar-expand-sm navbar-dark bg-dark\">\r\n");
      out.write("		<div class=\"container-fluid\">\r\n");
      out.write("			<a class=\"navbar-brand\" href=\"javascript:void(0)\">Yoon</a>\r\n");
      out.write("			<button class=\"navbar-toggler\" type=\"button\"\r\n");
      out.write("				data-bs-toggle=\"collapse\" data-bs-target=\"#mynavbar\">\r\n");
      out.write("				<span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("			</button>\r\n");
      out.write("			<div class=\"collapse navbar-collapse\" id=\"mynavbar\">\r\n");
      out.write("				<ul class=\"navbar-nav me-auto\">\r\n");
      out.write("					<li class=\"nav-item\">\r\n");
      out.write("					<a class=\"nav-link\" href=\"javascript:void(0)\">Link</a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("				\r\n");
      out.write("				<ul class=\"navbar-nav d-flex\">\r\n");
      out.write("				<!-- 로그인 했을 때 -->\r\n");
      out.write("				<!-- 로그인 했을 때 -->\r\n");
      out.write("				");
 
				String id = (String) session.getAttribute("username"); 
				if( id != null){   
      out.write("\r\n");
      out.write("					<li class=\"nav-item\">\r\n");
      out.write("						<a class=\"nav-link\" href=\"jsp022_my.jsp\">");
      out.print(id );
      out.write("</a>\r\n");
      out.write("					</li>\r\n");
      out.write("					<li class=\"nav-item\">\r\n");
      out.write("						<a class=\"nav-link\" href=\"jsp022_Logout.jsp\">LOGOUT</a>\r\n");
      out.write("					</li>\r\n");
      out.write("				");
	}else{   
      out.write("\r\n");
      out.write("				<!-- 로그인 안했을 때 -->\r\n");
      out.write("				<!-- 로그인 안했을 때 -->\r\n");
      out.write("					<li class=\"nav-item\">\r\n");
      out.write("						<a class=\"nav-link\" href=\"jsp022_Login.jsp\">LOGIN</a>\r\n");
      out.write("					</li>\r\n");
      out.write("					<li class=\"nav-item\">\r\n");
      out.write("						<a class=\"nav-link\" href=\"javascript:void(0)\">JOIN</a>\r\n");
      out.write("					</li>\r\n");
      out.write("				");
 	}   
      out.write("\r\n");
      out.write("				</ul>\r\n");
      out.write("				\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</nav>\r\n");
      out.write("\r\n");
      out.write("	<!-- navrbar -->\r\n");
      out.write("<!-- navrbar -->");
      out.write("\r\n");
      out.write("<!-- navrbar -->\r\n");
      out.write("<!-- navrbar -->\r\n");
      out.write("\r\n");
      out.write("	<div class=\"container card  my-5\">\r\n");
      out.write("		<h3 class=\"card-header mb-3\"> LOGIN </h3> \r\n");
      out.write("		<p style=\"text-align:center; \"><img src=\"images/login.png\" alt=\"login\"/></p>  \r\n");
      out.write("		<form action=\"");
      out.print(request.getContextPath() );
      out.write("/user_join\"  method=\"post\"  onsubmit=\"return  form()\">\r\n");
      out.write("			<div class=\"my-3\">\r\n");
      out.write("				<label for=\"name\"   class=\"form-label\">아이디 </label>\r\n");
      out.write("				<input type=\"text\"  class=\"form-control\"  id=\"name\"  name=\"name\" />      \r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"my-3\">\r\n");
      out.write("				<label for=\"pass\"       class=\"form-label\">비밀번호 </label>\r\n");
      out.write("				<input type=\"password\"  class=\"form-control\"  id=\"pass\"  name=\"pass\" />      \r\n");
      out.write("			</div>		\r\n");
      out.write("			<div class=\"my-3\">\r\n");
      out.write("				<input type=\"checkbox\"   id=\"check\"  name=\"remember\" />      \r\n");
      out.write("				<label for=\"check\"       class=\"form-label\">아이디 기억하기 </label>\r\n");
      out.write("			</div>	\r\n");
      out.write("			<div class=\"my-3 text-end\"> \r\n");
      out.write("				<input type=\"submit\" title=\"login 하러가기\" class=\"btn btn-success\" value=\"회원가입\" />      \r\n");
      out.write("			</div>								\r\n");
      out.write("		</form>\r\n");
      out.write("		<script>\r\n");
      out.write("		//Q1\r\n");
      out.write("		function form(){\r\n");
      out.write("			let  name = document.getElementById(\"name\");\r\n");
      out.write("			let  pass = document.querySelector(\"#pass\");\r\n");
      out.write("			//console.log(name.value+\"/\"+pass.value);\r\n");
      out.write("			\r\n");
      out.write("			if(name.value ==\"\" ){  alert(\"빈칸입니다. \\n확인해주세요\");  name.focus();  return false; } \r\n");
      out.write("			if(pass.value ==\"\" ){  alert(\"빈칸입니다. \\n확인해주세요\");  pass.focus();  return false; }\r\n");
      out.write("		}\r\n");
      out.write("		</script>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("<!-- footer.jsp -->\r\n");
      out.write("<!-- footer.jsp -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- footer.jsp -->\r\n");
      out.write("<!-- footer.jsp -->\r\n");
      out.write("<!-- 파일분리 : jsp022_footer.js -->\r\n");
      out.write("<footer class =\"container-fluid text-center text-white bg-secondary p-5\">\r\n");
      out.write("	copyright &copy; 2025 안윤기 all rights reservered.\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html> ");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("<!-- \r\n");
      out.write("	<div class=\"container card  my-5\">\r\n");
      out.write("		<pre class=\"bg-success text-white py-3\">\r\n");
      out.write("		Q1. 아이디와 비밀번호 빈칸검사\r\n");
      out.write("		Q2. 처리경로 : jsp022_login_action.jsp  / 아이디와 비밀번호 데이터값 노출안됨.\r\n");
      out.write("		Q3. jsp022_login_action.jsp \r\n");
      out.write("		    - 데이터값 넘겨받기\r\n");
      out.write("		    - 드라이버연동 / db연동 / sql처리 / 결과값 확인\r\n");
      out.write("		    - 아이디와 비밀번호가 같은지 member에서 검색\r\n");
      out.write("		    - 찾았으면 [경로안바뀌게] , 보이는 화면은 jsp022_my.jsp 페이지로 넘어가기 / \r\n");
      out.write("		      못찾았으면 정보를 확인해주세요~ 알림창띄우고 로그인페이지로  jsp022_login.jsp 페이지로\r\n");
      out.write("		    \r\n");
      out.write("		    select count(*) from member  where name=?  and pass=?\r\n");
      out.write("		    \r\n");
      out.write("			mysql> desc member;\r\n");
      out.write("			+-------+--------------+------+-----+---------+----------------+\r\n");
      out.write("			| Field | Type         | Null | Key | Default | Extra          |\r\n");
      out.write("			+-------+--------------+------+-----+---------+----------------+\r\n");
      out.write("			| no    | int          | NO   | PRI | NULL    | auto_increment |  id를 name로 체크!\r\n");
      out.write("			| name  | varchar(100) | NO   |     | NULL    |                |\r\n");
      out.write("			| pass  | varchar(50)  | NO   |     | NULL    |                |\r\n");
      out.write("			+-------+--------------+------+-----+---------+----------------+\r\n");
      out.write("			3 rows in set (0.00 sec)\r\n");
      out.write("			\r\n");
      out.write("			mysql> select * from member;\r\n");
      out.write("			+----+--------+------+\r\n");
      out.write("			| no | name   | pass |\r\n");
      out.write("			+----+--------+------+\r\n");
      out.write("			|  1 | first  | 11   |\r\n");
      out.write("			|  2 | second | 22   |\r\n");
      out.write("			|  3 | third  | 33   |\r\n");
      out.write("			|  4 | fourth | 44   |\r\n");
      out.write("			+----+--------+------+\r\n");
      out.write("			4 rows in set (0.00 sec)\r\n");
      out.write("\r\n");
      out.write("		Q4. login.jsp/ my.jsp 두군데서 사용할 header 만들기\r\n");
      out.write("		Q5. 로그인시 아이디 유지하기 (session)\r\n");
      out.write("		Q6. 로그인시 아이디유지하기 체크하면 아이디 유지하게 만들기  (cookie)\r\n");
      out.write("		</pre>\r\n");
      out.write("	</div> -->\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
